#!/usr/bin/env bash
# bootstrap-nodered-flatfile.sh — Phase 1A bootstrap for the flat-file `nodered` user.
#
# Idempotent. Safe to re-run. Only does work on the first invocation; subsequent runs
# verify state and exit cleanly.
#
# What this does:
#   1. Generate /opt/tak/certs/files/nodered.pem and .key via TAK's makeCert.sh (if missing)
#   2. Add a <user identifier="nodered" role="ROLE_USER"> entry to UserAuthenticationFile.xml
#      with explicit groupList membership in the configured DataSync group (default:
#      DATASYNC-FEEDS — override with NODERED_GROUP env var)
#   3. Restart TAK Server to load the new flat-file user
#   4. chmod 644 the cert files so the Node-RED container (UID 1000) can read them
#   5. Verify the user is loaded via UserManager.jar
#
# Usage:
#   sudo bash scripts/bootstrap-nodered-flatfile.sh                  # default group: DATASYNC-FEEDS
#   sudo NODERED_GROUP=MY-GROUP bash scripts/bootstrap-nodered-flatfile.sh
#   sudo bash scripts/bootstrap-nodered-flatfile.sh --check          # check state only, no changes
#   sudo bash scripts/bootstrap-nodered-flatfile.sh --remove         # remove user + restart (cert files left in place)
#
# Prerequisites:
#   - TAK Server installed at /opt/tak
#   - You have completed Phase 0 (docs/SPIKE-flatfile-nodered.md) and verified the approach works
#     on this install. THIS SCRIPT MAKES MISSION-CRITICAL CHANGES — do not run it before validating.

set -euo pipefail

CMD="${1:-apply}"
NODERED_GROUP="${NODERED_GROUP:-DATASYNC-FEEDS}"
TAK_DIR="/opt/tak"
CERT_DIR="$TAK_DIR/certs/files"
UAF="$TAK_DIR/UserAuthenticationFile.xml"
USERMGR="$TAK_DIR/utils/UserManager.jar"

need_root() {
  if [ "$EUID" -ne 0 ]; then
    echo "ERROR: must run as root (sudo)" >&2
    exit 1
  fi
}

check_prereqs() {
  if [ ! -d "$TAK_DIR" ]; then
    echo "ERROR: $TAK_DIR not found — TAK Server not installed?" >&2
    exit 1
  fi
  if [ ! -f "$UAF" ]; then
    echo "ERROR: $UAF not found — flat-file auth not enabled in CoreConfig" >&2
    echo "  Check /opt/tak/CoreConfig.xml for <auth> block referencing <file>" >&2
    exit 1
  fi
}

check_state() {
  echo "==> Bootstrap state check"
  echo "    Group:              $NODERED_GROUP"
  if [ -f "$CERT_DIR/nodered.pem" ] && [ -f "$CERT_DIR/nodered.key" ]; then
    echo "    Cert files:         present ($CERT_DIR/nodered.pem)"
  else
    echo "    Cert files:         MISSING (will be generated by makeCert.sh)"
  fi
  if grep -q 'identifier="nodered"' "$UAF" 2>/dev/null; then
    echo "    UserAuth entry:     PRESENT in $UAF"
    grep -A1 'identifier="nodered"' "$UAF" | sed 's/^/      /'
  else
    echo "    UserAuth entry:     MISSING (will be added)"
  fi
  if [ -f "$USERMGR" ]; then
    if java -jar "$USERMGR" listusers 2>/dev/null | grep -q '^nodered\b'; then
      echo "    Loaded by TAK:      YES (UserManager.jar listusers shows nodered)"
    else
      echo "    Loaded by TAK:      NO (will be loaded after restart)"
    fi
  fi
  if [ -f "$CERT_DIR/nodered.key" ]; then
    perms="$(stat -c '%a' "$CERT_DIR/nodered.key" 2>/dev/null || stat -f '%A' "$CERT_DIR/nodered.key" 2>/dev/null || echo '???')"
    echo "    nodered.key perms:  $perms (need >= 644 for Node-RED container UID 1000)"
  fi
}

generate_cert() {
  if [ -f "$CERT_DIR/nodered.pem" ] && [ -f "$CERT_DIR/nodered.key" ]; then
    echo "==> Cert already exists — skipping makeCert.sh"
    return 0
  fi
  echo "==> Generating nodered cert via makeCert.sh"
  pushd "$TAK_DIR/certs" >/dev/null
  echo "y" | sudo -u tak ./makeCert.sh client nodered
  popd >/dev/null
  if [ ! -f "$CERT_DIR/nodered.pem" ] || [ ! -f "$CERT_DIR/nodered.key" ]; then
    echo "ERROR: cert generation did not produce expected files" >&2
    exit 1
  fi
  echo "    Generated: $CERT_DIR/nodered.pem and .key"
}

add_user_to_uaf() {
  if grep -q 'identifier="nodered"' "$UAF" 2>/dev/null; then
    echo "==> User 'nodered' already in $UAF — skipping XML edit"
    return 0
  fi
  echo "==> Adding nodered user to $UAF (group: $NODERED_GROUP)"
  # Backup before editing
  cp "$UAF" "$UAF.pre-nodered-$(date +%Y%m%d-%H%M%S).bak"
  # Use python (already in TAK install for related tooling) to safely insert via XML parser
  python3 - "$UAF" "$NODERED_GROUP" <<'PYEOF'
import sys, xml.etree.ElementTree as ET
uaf_path, group = sys.argv[1], sys.argv[2]
tree = ET.parse(uaf_path)
root = tree.getroot()
# Match TAK Server's existing schema: lowercase <user> elements at the root.
# The exact attributes/children may vary by TAK Server version. We use the most
# widely-supported form: identifier + role attributes, with a <groupList> child.
existing = [u for u in root.iter() if u.tag.endswith('user') and u.get('identifier') == 'nodered']
if existing:
    print('  (already present after re-read — no change)')
    sys.exit(0)
# Determine namespace if any
ns = ''
if root.tag.startswith('{'):
    ns = root.tag.split('}')[0] + '}'
# Build the new user element.
user = ET.SubElement(root, ns + 'user')
user.set('identifier', 'nodered')
user.set('passwordHashed', 'false')
user.set('role', 'ROLE_USER')
# groupList child — the schema we observed in spike testing accepts <groupList>NAME</groupList>.
# If your install requires <groupListIN>/<groupListOUT> (older 5.x), edit this file by hand
# after the script writes it.
gl = ET.SubElement(user, ns + 'groupList')
gl.text = group
# Pretty-print preservation: ET doesn't preserve whitespace well, but TAK Server's parser
# accepts compact form. Write back.
tree.write(uaf_path, xml_declaration=True, encoding='UTF-8')
print(f'  Added <user identifier="nodered" role="ROLE_USER"> with <groupList>{group}</groupList>')
PYEOF
  echo "    Backup saved next to $UAF (.pre-nodered-*.bak)"
}

remove_user_from_uaf() {
  if ! grep -q 'identifier="nodered"' "$UAF" 2>/dev/null; then
    echo "==> User 'nodered' not in $UAF — nothing to remove"
    return 0
  fi
  echo "==> Removing nodered user from $UAF"
  cp "$UAF" "$UAF.pre-remove-$(date +%Y%m%d-%H%M%S).bak"
  python3 - "$UAF" <<'PYEOF'
import sys, xml.etree.ElementTree as ET
uaf_path = sys.argv[1]
tree = ET.parse(uaf_path)
root = tree.getroot()
removed = False
for parent in root.iter():
    for child in list(parent):
        if child.tag.endswith('user') and child.get('identifier') == 'nodered':
            parent.remove(child)
            removed = True
if removed:
    tree.write(uaf_path, xml_declaration=True, encoding='UTF-8')
    print('  Removed nodered user element')
else:
    print('  (no element found at parse time)')
PYEOF
}

restart_takserver() {
  echo "==> Restarting TAK Server to load $UAF changes"
  systemctl restart takserver
  echo "    Waiting for takserver to be ready (up to 90s)..."
  for i in $(seq 1 18); do
    if ss -tlnp 2>/dev/null | grep -q ':8089\b'; then
      echo "    TAK Server listening on :8089 (took ~$((i*5))s)"
      return 0
    fi
    sleep 5
  done
  echo "WARNING: takserver did not start listening on :8089 within 90s — check 'sudo systemctl status takserver'" >&2
}

fix_perms() {
  if [ -f "$CERT_DIR/nodered.key" ]; then
    chmod 644 "$CERT_DIR/nodered.key"
    chmod 644 "$CERT_DIR/nodered.pem"
    echo "==> chmod 644 on $CERT_DIR/nodered.{pem,key} (so Node-RED container UID 1000 can read)"
  fi
}

verify() {
  if [ -f "$USERMGR" ]; then
    echo "==> Verifying via UserManager.jar"
    if java -jar "$USERMGR" listusers 2>/dev/null | grep -q '^nodered\b'; then
      echo "    PASS: nodered is listed by UserManager.jar"
    else
      echo "    FAIL: nodered NOT listed by UserManager.jar — check XML schema or restart status" >&2
      return 1
    fi
  else
    echo "    (skipping UserManager verification — $USERMGR not found)"
  fi
}

case "$CMD" in
  apply)
    need_root
    check_prereqs
    check_state
    echo
    generate_cert
    add_user_to_uaf
    restart_takserver
    fix_perms
    verify || true
    echo
    echo "==> Done. Next steps:"
    echo "    1. Run docs/SPIKE-flatfile-nodered.md tests T1-T6 with /opt/tak/certs/files/nodered.pem"
    echo "    2. If T1+T3 pass: bash nodered/deploy.sh — auto-detects nodered.pem and switches Node-RED to it"
    echo "    3. After deploy: re-enter the TLS passphrase ('atakatak' default) once in the Node-RED editor"
    ;;
  --check|check)
    check_prereqs
    check_state
    ;;
  --remove|remove)
    need_root
    check_prereqs
    remove_user_from_uaf
    restart_takserver
    echo "==> Cert files left in place at $CERT_DIR/nodered.{pem,key} — delete manually if rotating"
    ;;
  *)
    echo "Usage: $0 {apply|check|remove}" >&2
    exit 2
    ;;
esac
